DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;


CREATE TABLE Comment (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author TEXT UNIQUE NOT NULL,
  FOREIGN KEY (productID) REFERENCES Product (id),
  commentText TEXT NOT NULL
);


CREATE TABLE Product (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  price FLOAT NOT NULL,
  description TEXT NOT NULL,
  location TEXT NOT NULL
);