# Generated by Django 3.1.3 on 2020-12-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
